# Generated by Django 4.2 on 2023-04-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('destination', models.CharField(max_length=60)),
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
            ],
        ),
    ]
