# Generated by Django 4.2 on 2023-05-14 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_home_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='response',
        ),
    ]
