# Generated by Django 4.2 on 2023-05-22 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_remove_home_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='responses',
            field=models.CharField(default='No response yet...', max_length=5000),
        ),
        migrations.AddField(
            model_name='home',
            name='user',
            field=models.OneToOneField(default=home.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
