# Generated by Django 4.2 on 2023-05-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_home_responses_home_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='activity',
            field=models.CharField(default='No planned activities...', max_length=2000),
        ),
        migrations.AlterField(
            model_name='home',
            name='responses',
            field=models.CharField(default='N/A', max_length=5000),
        ),
    ]
