# Generated by Django 4.2 on 2023-05-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_home_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='activity',
            field=models.CharField(default='N/A', max_length=30000),
        ),
        migrations.AlterField(
            model_name='home',
            name='responses',
            field=models.CharField(default='N/A', max_length=50000),
        ),
    ]
