# Generated by Django 4.2 on 2023-05-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_home_returntime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='returnTime',
        ),
        migrations.AlterField(
            model_name='home',
            name='time',
            field=models.CharField(max_length=60),
        ),
    ]
