# Generated by Django 4.2 on 2023-05-25 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_home_returntime_alter_home_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='home',
            name='responses',
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(default='N/A', max_length=60000)),
                ('response', models.CharField(max_length=50000)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='home.home')),
            ],
        ),
    ]
