# Generated by Django 4.2 on 2023-05-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_home_activity_home_responses_delete_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='activity',
            field=models.CharField(default='N/A', max_length=100000),
        ),
    ]
